import fs from "node:fs";
import path from "node:path";
import { ensureDir } from "../utils/fs.js";
import { redactText } from "./redact.js";
import type { EcosystemInfo } from "./ecosystems.js";
import type { FailureInfo } from "./extract.js";
import type { RuntimeInfo } from "./runtime.js";
import { formatEnvironment } from "./runtime.js";

export interface BundleInput {
  sourceDisplay: string;
  sourceUrl?: string;
  ecosystem: EcosystemInfo;
  runtime: RuntimeInfo;
  failure: FailureInfo;
  redactedLogs: string;
  redactions: number;
  runMeta?: {
    workflow?: string;
    branch?: string;
    sha?: string;
    job?: string;
    conclusion?: string;
  };
}

export interface BundleResult {
  outDir: string;
  files: string[];
}

function shQuote(cmd: string): string {
  // For display only; the command is embedded verbatim in the script.
  return cmd;
}

function installBlock(eco: EcosystemInfo): string {
  switch (eco.id) {
    case "npm":
      return ["if [ -f package-lock.json ]; then npm ci; else npm install; fi"].join(
        "\n",
      );
    case "pnpm":
      return [
        'if ! command -v pnpm >/dev/null 2>&1; then echo "pnpm not found. Install: npm install -g pnpm (Termux: npm install -g pnpm)"; exit 1; fi',
        "if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile; else pnpm install; fi",
      ].join("\n");
    case "yarn":
      return [
        'if ! command -v yarn >/dev/null 2>&1; then echo "yarn not found. Install: npm install -g yarn"; exit 1; fi',
        "if [ -f yarn.lock ]; then yarn install --frozen-lockfile; else yarn install; fi",
      ].join("\n");
    case "pip":
      return [
        "python3 -m pip install --upgrade pip",
        "if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt;",
        'elif [ -f pyproject.toml ]; then python3 -m pip install -e ".[test]" 2>/dev/null || python3 -m pip install -e . 2>/dev/null || echo "(no installable package; continuing)";',
        'else echo "(no requirements.txt/pyproject.toml found; skipping install)"; fi',
      ].join("\n");
    case "uv":
      return [
        'if ! command -v uv >/dev/null 2>&1; then echo "uv not found. Install: curl -LsSf https://astral.sh/uv/install.sh | sh"; exit 1; fi',
        'uv sync || echo "(uv sync failed/partial; continuing)"',
      ].join("\n");
    case "cargo":
      return [
        'if ! command -v cargo >/dev/null 2>&1; then echo "cargo not found. Install Rust: https://rustup.rs (Termux: pkg install rust)"; exit 1; fi',
        "cargo fetch || true",
      ].join("\n");
    case "go":
      return [
        'if ! command -v go >/dev/null 2>&1; then echo "go not found. Install Go (Termux: pkg install golang)"; exit 1; fi',
        "go mod download || true",
      ].join("\n");
    default:
      return 'echo "(unknown ecosystem) install your dependencies manually, then re-run the failing command below."';
  }
}

function reproCommandFor(eco: EcosystemInfo, failure: FailureInfo): string {
  if (failure.reproCommand) return shQuote(failure.reproCommand);
  return shQuote(eco.testCommand);
}

export function buildReproduceSh(input: BundleInput): string {
  const cmd = reproCommandFor(input.ecosystem, input.failure);
  return `#!/usr/bin/env bash
# Auto-generated by actionrepro. Reproduces a failed CI run locally.
# Source: ${input.sourceDisplay}
# Ecosystem: ${input.ecosystem.id} (confidence: ${input.ecosystem.confidence})
# No secrets are embedded in this file. All logs were redacted (${input.redactions} redactions).
set -euo pipefail

echo "==> actionrepro: ecosystem=${input.ecosystem.id} confidence=${input.ecosystem.confidence}"
echo "==> evidence: ${input.ecosystem.evidence.join("; ") || "n/a"}"
echo "==> failure: ${singleLine(input.failure.summary)}"
${input.failure.exitCode !== undefined ? `echo "==> CI exit code: ${input.failure.exitCode}"` : ""}
echo ""

echo "==> Step 1/2: install dependencies"
${installBlock(input.ecosystem)}

echo ""
echo "==> Step 2/2: reproduce failure"
echo "==> running: ${cmd}"
${cmd}

echo ""
echo "==> Done. If the command above fails the same way as CI, you reproduced it."
`;
}

export function buildReproducePs1(input: BundleInput): string {
  const cmd = reproCommandFor(input.ecosystem, input.failure);
  const installPs = psInstall(input.ecosystem);
  return `# Auto-generated by actionrepro (Windows PowerShell).
# Source: ${input.sourceDisplay}
# Ecosystem: ${input.ecosystem.id}
$ErrorActionPreference = "Stop"
Write-Host "==> actionrepro: ecosystem=${input.ecosystem.id}"
Write-Host "==> failure: ${singleLine(input.failure.summary)}"
Write-Host ""
Write-Host "==> Step 1/2: install dependencies"
${installPs}
Write-Host ""
Write-Host "==> Step 2/2: reproduce failure"
Write-Host "==> running: ${cmd}"
Invoke-Expression "${psEscape(cmd)}"
Write-Host ""
Write-Host "==> Done."
`;
}

function psInstall(eco: EcosystemInfo): string {
  switch (eco.id) {
    case "npm":
      return `if (Test-Path package-lock.json) { npm ci } else { npm install }`;
    case "pnpm":
      return `pnpm install --frozen-lockfile`;
    case "yarn":
      return `yarn install --frozen-lockfile`;
    case "pip":
      return `python -m pip install --upgrade pip\nif (Test-Path requirements.txt) { python -m pip install -r requirements.txt }`;
    case "uv":
      return `uv sync`;
    case "cargo":
      return `cargo fetch`;
    case "go":
      return `go mod download`;
    default:
      return `Write-Host "(unknown ecosystem) install dependencies manually."`;
  }
}

function psEscape(cmd: string): string {
  return cmd.replace(/"/g, '`"');
}

function singleLine(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

export function buildBundleReadme(input: BundleInput): string {
  const meta = input.runMeta;
  return `# ActionRepro bundle

Reproduces a failed CI run locally. Generated deterministically (no LLM).

## Source

- Input: \`${input.sourceDisplay}\`
${input.sourceUrl ? `- Run: ${input.sourceUrl}\n` : ""}${meta?.workflow ? `- Workflow: ${meta.workflow}\n` : ""}${meta?.job ? `- Failing job: ${meta.job}\n` : ""}${meta?.branch ? `- Branch: ${meta.branch}\n` : ""}${meta?.sha ? `- SHA: \`${meta.sha}\`\n` : ""}
## Failure

> ${singleLine(input.failure.summary)}

${input.failure.failingStep ? `- Failing step: \`${input.failure.failingStep}\`\n` : ""}${input.failure.exitCode !== undefined ? `- Exit code: \`${input.failure.exitCode}\`\n` : ""}- Closest repro command: \`${reproCommandFor(input.ecosystem, input.failure)}\`
- Hint: ${input.failure.hint}

<details><summary>Error context (redacted)</summary>

\`\`\`
${input.failure.errorLines.slice(0, 40).join("\n")}
\`\`\`

</details>

## Environment (CI)

\`\`\`
${formatEnvironment(input.runtime)}
\`\`\`

- Ecosystem: \`${input.ecosystem.id}\` (confidence: ${input.ecosystem.confidence})
- Evidence: ${input.ecosystem.evidence.join("; ") || "n/a"}
- Install: \`${input.ecosystem.installCommand}\`
- Test: \`${input.ecosystem.testCommand}\`

## Reproduce

Linux / macOS / Termux (recommended):

\`\`\bash
chmod +x reproduce.sh
./reproduce.sh
\`\`\`

Windows (PowerShell):

\`\`\`powershell
.\\reproduce.ps1
\`\`\`

Termux notes:

\`\`\bash
pkg update && pkg install -y git nodejs python
# Rust: pkg install rust
# Go: pkg install golang
./reproduce.sh
\`\`\`

No Docker required. No telemetry. Secrets were redacted (${input.redactions} replacements); verify before sharing.

## Files

- \`reproduce.sh\` — bash reproduction script
- \`reproduce.ps1\` — PowerShell reproduction script
- \`failure.txt\` — redacted failure excerpt + full error context
- \`environment.txt\` — CI runner/runtime details
- \`repro.json\` — machine-readable metadata (redacted)
- \`README.md\` — this file
`;
}

export function buildFailureTxt(input: BundleInput): string {
  const meta = input.runMeta;
  const header = [
    `source: ${input.sourceDisplay}`,
    input.sourceUrl ? `run: ${input.sourceUrl}` : null,
    meta?.workflow ? `workflow: ${meta.workflow}` : null,
    meta?.job ? `job: ${meta.job}` : null,
    input.failure.failingStep ? `step: ${input.failure.failingStep}` : null,
    input.failure.exitCode !== undefined ? `exit-code: ${input.failure.exitCode}` : null,
    `ecosystem: ${input.ecosystem.id}`,
    `repro: ${reproCommandFor(input.ecosystem, input.failure)}`,
    `redactions: ${input.redactions}`,
    ``,
    `summary: ${singleLine(input.failure.summary)}`,
    `hint: ${input.failure.hint}`,
    ``,
    `--- error context (redacted) ---`,
  ].filter((x): x is string => x !== null);
  return header.join("\n") + "\n" + input.failure.errorLines.join("\n") + "\n";
}

export function buildEnvironmentTxt(input: BundleInput): string {
  return [
    `source: ${input.sourceDisplay}`,
    input.sourceUrl ? `run: ${input.sourceUrl}` : null,
    ``,
    formatEnvironment(input.runtime),
    ``,
    `ecosystem: ${input.ecosystem.id} (confidence: ${input.ecosystem.confidence})`,
    `evidence: ${input.ecosystem.evidence.join("; ") || "n/a"}`,
    `install: ${input.ecosystem.installCommand}`,
    `test: ${input.ecosystem.testCommand}`,
    `hint: ${input.ecosystem.runHint}`,
    ``,
    `Generated by actionrepro. Secrets redacted (${input.redactions}).`,
  ]
    .filter((x): x is string => x !== null)
    .join("\n");
}

export function createBundle(input: BundleInput, outDir: string): BundleResult {
  ensureDir(outDir);
  const files: string[] = [];

  const sh = buildReproduceSh(input);
  const ps1 = buildReproducePs1(input);
  const readme = buildBundleReadme(input);
  const failure = buildFailureTxt(input);
  const envTxt = buildEnvironmentTxt(input);
  const meta = {
    tool: "actionrepro",
    source: input.sourceDisplay,
    runUrl: input.sourceUrl ?? null,
    ecosystem: input.ecosystem.id,
    ecosystemConfidence: input.ecosystem.confidence,
    evidence: input.ecosystem.evidence,
    failure: {
      summary: singleLine(input.failure.summary),
      failingJob: input.failure.failingJob ?? input.runMeta?.job ?? null,
      failingStep: input.failure.failingStep ?? null,
      exitCode: input.failure.exitCode ?? null,
      reproCommand: reproCommandFor(input.ecosystem, input.failure),
      hint: input.failure.hint,
    },
    runtime: input.runtime,
    redactions: input.redactions,
    generatedAt: new Date().toISOString(),
  };

  // Final safety: redact every file once more before writing.
  const write = (name: string, content: string, executable = false) => {
    const safe = redactText(content).text;
    const fp = `${outDir}/${name}`;
    fs.writeFileSync(fp, safe, "utf8");
    if (executable) {
      try {
        fs.chmodSync(fp, 0o755);
      } catch {
        /* Windows: ignore chmod */
      }
    }
    files.push(fp);
  };

  write("reproduce.sh", sh, true);
  write("reproduce.ps1", ps1);
  write("README.md", readme);
  write("failure.txt", failure);
  write("environment.txt", envTxt);
  write("repro.json", JSON.stringify(meta, null, 2) + "\n");

  void path;
  return { outDir, files };
}
